export const specialties = [
  "Anesthesia ","Dentistry","Dermatology","Ear, nose and throat (ENT)","Endocrinology","Gastroenterology","General surgery",
  "Hematology","Hepatology","Internal Medicine","Nephrology","Neurology","Obstetrics and Gynecology","Oncology","Ophthalmology","Orthopedics","Pediatrics",
  "Plastic surgery","Psychiatry","Rheumatology","Urology",];
export  const cairoenglishRegions = [
    'downtown',
    'Zamalek',
    'Abbasiya',
    'El Nozha',
    'Nasr City',
    'New Cairo',
    'New Heliopolis',
    'Badr',
    'Al Abour',
    'Al Shorouk',
    'Madinaty',
    '10th of Ramadan city',
    'Banha City',
    'New Administrative Capital',
    'The First Settlement',
    'The 3th Settlement',
    'The 5th Settlement',
    'El Basatin',
    'Al-Tabin',
    'Al-Tunisia',
    'Al Jazeera',
    'El-Gamaleya',
    'ELHussein',
    'Al-Helmiya',
    'Al-Helmiya Algdida',
    'Caligh Al-Maamun',
    'Al-Darb Al-Ahmar',
    'Duwaiqa',
    'El Zawya El Hamraa',
    'El Zaitoun',
    'El Sahel',
    'Shubra',
    'Sharabiya',
    'Rod El-Farag',
    'As-Salam',
    'Al Sayeda Zeinab',
    'El Sagha',
    'Fajjala',
    'Katameya',
    'lotus',
    'Al Marj',
    'South Investors Area',
    'North Investors Area',
    'El Matariyya',
    'El Mokattam',
    'Al-Mounira',
    'New Mounira',
    'Musky',
    'Al-Waili',
    'Bab El Sharia',
    'Bab Al-Luq',
    'Bulaq Abu Al-Ela',
    'Sakanat El Maadi',
    'Maadi Gardens',
    'Maadi',
    'garden City',
    'Rhoda Island',
    'Geser El-Swies',
    'Al Safarat',
    'Kobba Gardens',
    'Al-Khalifa District',
    'Dar AISalaam',
    'Saray Al-Qubba',
    'Abdeen',
    'Abboud',
    'Kasr Al-Nile',
    'kotsika',
    'El-Banafseg',
    'Al Rehab',
    'Al Narges',
    'El yasmine',
    // 'Nasr City',
    'Sheraton Airport Residences',
    'Heliopolis',
    'Ancient Egypt',
    'Mansheyat Nasser',
  ];

  export const gizaenglishRegions = [
    "October",
    "October Gardens",
    "Sheikh Zayed",
    "Agoza",
    "Mohandseen",
    "Dokki",
    "Bhoos",
    "Abu Rawash",
    "Imbaba",
    "Kit Kat",
    "Ard El Lewa",
    "Al-Warraq",
    "Bulaq Dakror",
    "Meet Okba",
    "Giza district",
    "Giza Center",
    "Pyramid",
    "Mariouteya",
    "Tersa",
    "Faisal",
    "Al-Munib",
    "The Pyramid gardens",
    "Awseem",
    "Al-Badrasheen",
    "Barajil",
    "Hawamdiya",
    "Remaia",
    "Sahfeen",
    "El Saaf",
    "Aziziyya",
    "Umrania",
    "Ayat",
    "Mansouriya",
    "Bashtil",
    "Dahab Island",
    "Dahshur",
    "Saft",
    "Sumed",
    "Kardasa",
    "Kafr Tohormos",
    "Nahya",
  ];

export  const governorate=["Cairo","Giza"]
